add IfStmt, forStmt, while, Inc & Dec, Cmp Stmt
lifting-bits/pillar pull request #3
Opened 2024-01-03 16:43 UTC by biniyam-mt

2024-01-03 17:02 UTC, pgoodman requested changes

2024-01-03 17:02 UTC, pgoodman commented on lib/ASTStmt.cpp
> +          if (mlir::isa<vast::hl::ValueYieldOp>(op) || mlir::isa<vast::hl::CondYieldOp>(op) || mlir::isa<vast::hl::PostIncOp>(op))
Why is the postincop in here? I assume for the inductive part of a `for` loop, but you can put whatever you want in there.

2024-01-03 17:02 UTC, pgoodman commented on lib/ASTStmt.cpp
> +          if (mlir::isa<vast::hl::ValueYieldOp>(op) || mlir::isa<vast::hl::CondYieldOp>(op) || mlir::isa<vast::hl::PostIncOp>(op))
Maybe the thing to make sure about is that `ElideFromCompontStmt` doesn't skip things like `PostInctOp`.

2024-01-03 17:02 UTC, pgoodman commented on lib/ASTStmt.cpp
> +      for (mlir::Block &block : op.getCondRegion().getBlocks())
This seems like a pattern, maybe wrap in a utility method.

2024-01-03 17:02 UTC, pgoodman commented on lib/ASTStmt.cpp
> +        llvm::TypeSwitch<mlir::Operation *>(&op)
`ret = nullptr;`

But really, you can use the second template operand to `TypeSwitch`, as follows:

```c++
llvm::TypeSwitch<mlir::Operation *, clang::Stmt *>(&op)
...
```

Then you can directly `return` the statements from your lambdas. The default case might need a `) -> clang::Stmt * {` as `nullptr` is technically a `std::nullptr_t`.

2024-01-04 18:28 UTC, biniyam-mt commented on lib/ASTStmt.cpp
> +          if (mlir::isa<vast::hl::ValueYieldOp>(op) || mlir::isa<vast::hl::CondYieldOp>(op) || mlir::isa<vast::hl::PostIncOp>(op))
I'm sharing `LiftBlockExpr` because vast returns a region for `inc` and I want it as an `Expr`

2024-01-04 18:30 UTC, biniyam-mt commented on lib/ASTStmt.cpp
> +      for (mlir::Block &block : op.getCondRegion().getBlocks())
just the for loop or all three lines?

2024-01-04 19:10 UTC, merged